repos:
-   repo: https://github.com/CanalTP/navitia-pre-commit
    rev: master
    hooks:
    -   id: clang-format-6.0
        verbose: true
        exclude: ^source/third_party/
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args: [-i]
